mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<username>/', views.AccountDetailView.as_view(), name='userdetail'),
    path('icon/edit/', views.IconEdit.as_view(), name='icon_edit'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'posts'

urlpatterns = [
    path('new/', login_required(views.New.as_view()), name='new'),
    path('', login_required(views.Index.as_view()), name='index'),
    path('<postId>/like/', login_required(views.Likes.as_view()), name='like'),
    path('<postId>/comment/',
         login_required(views.AddComment.as_view()), name='comment'),
    path('<int:pk>/delete/',
         login_required(views.PostDelete.as_view()), name='delete'),
]

mysite/templates/base/app.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>ツイーゴ</title>
    {% load static %}
    <!-- 必要なライブラリインポート -->

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
        integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'base/app.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'posts/index.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'accounts/user_detail.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'accounts/icon_edit.css' %}" type="text/css">


    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-dark bg-primary box-shadow  scrolling-navbar">
            <a class="navbar-brand" href="/">
                <span id="appname">ツイーゴ</span>

            </a>
            <ul class="navbar-nav flex-row ml-md-auto">
                <!-- ここから追加 -->
                {% if user.id is None %}
                <!-- ログインしていなかったらこっち -->
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">新規登録　</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">ログイン　</a></li>
                {% else %}
                <!-- ログインしていたらこっち -->
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:index' %}">ディスカバリー　</a></li>
                <li class="nav-item"><a class="nav-link" href="/accounts/{{ user.username }}">マイページ　</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:new' %}">投稿　</a></li>
                <!--ここを編集-->
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">ログアウト　</a></li>
                {% endif %}
                <!-- 追加ここまで -->
            </ul>
        </nav>
    </header>
    <main>
        {% block contents %}{% endblock %}
    </main>
</body>

</html>