mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'posts'

urlpatterns = [
    path('new/', login_required(views.New.as_view()), name='new'),
    path('', login_required(views.Index.as_view()), name='index'),
    path('<postId>/like/', login_required(views.Likes.as_view()), name='like'),
    path('<postId>/comment/',
         login_required(views.AddComment.as_view()), name='comment'),
    path('<int:pk>/delete/',
         login_required(views.PostDelete.as_view()), name='delete'),
]

mysite/posts/models.py
from django.db import models
from accounts.models import User

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(
        'accounts.User', on_delete = models.CASCADE,
    )
    title = models.CharField(
        max_length = 200,
    )
    text = models.TextField(

    )
    picture = models.ImageField(
        upload_to = "image/posts/",
        blank = True,
        null = True,
    )
    created_at = models.DateTimeField(
        auto_now_add = True,
        blank = True,
    )

class Comment(models.Model):
    author = models.ForeignKey(
        'accounts.User', on_delete = models.CASCADE,
    )

    post = models.ForeignKey(
        'posts.Post', on_delete = models.CASCADE,
    )

    text = models.TextField(
        blank = True,
    )

class Like(models.Model):
    author = models.ForeignKey(
        'accounts.User', on_delete = models.CASCADE,
    )

    post = models.ForeignKey(
        'posts.Post', on_delete = models.CASCADE,
    )

mysite/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("picture", "title", "text")

mysite/posts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DeleteView
from django.urls import reverse_lazy
from django.views import View


from .forms import PostForm
from .models import Post, Like, Comment

# Create your views here.


class New(CreateView):
    template_name = 'posts/new.html'
    form_class = PostForm
    success_url = reverse_lazy('posts:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(New, self).form_valid(form)


class Index(ListView):
    model = Post
    template_name = 'posts/index.html'
    #paginate_by = 20
    queryset = Post.objects.order_by('created_at').reverse()

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        like_list = {}
        comment_list = {}
        comment_list2 = {}
        login_user = self.request.user
        # すでに取得されている投稿リストを一件づつ取り出す
        for post in context['post_list']:
            # 取り出したものから「いいね!」を探してlike_listに格納する
            like_list[post.id] = Like.objects.filter(post=post)
            comment_list[post.id] = Comment.objects.filter(post=post)
        for post in context['post_list']:
            comments = []
            for comment in comment_list[post.id]:
                if post.author.id == login_user.id or comment.author.id == login_user.id:
                    comments.append(comment)
            comment_list2.update({post.id: comments})
        context['like_list'] = like_list
        context['login_user'] = login_user
        context['comment_list'] = comment_list2
        return context


class PostDelete(DeleteView):
    model = Post
    success_url = reverse_lazy('posts:index')
    template_name = 'posts/delete.html'


class Likes(View):
    model = Like

    slug_field = 'post'

    slug_url_kwarg = 'postId'

    def get(self, request, postId):
        post = Post.objects.get(id=postId)

        like = Like.objects.filter(author=self.request.user, post=post)

        like_list = {}
        comment_list = {}

        if like.exists():
            like.delete()
        else:
            like = Like(author=self.request.user, post=post)
            like.save()

        like_list[post.id] = Like.objects.filter(post=post)

        comment_list[post.id] = Comment.objects.filter(post=post)

        return render(request, 'posts/like.html', {
            'like_list': like_list,
            'post': post,
            'comment_list': comment_list
        })


class AddComment(View):

    def post(self, request, postId):
        like_list = {}
        comment_list = {}

        post = Post.objects.get(id=postId)

        text = request.POST["comment"]

        comment = Comment(author=self.request.user, post=post, text=text)

        comment.save()

        like_list[post.id] = Like.objects.filter(post=post)

        comment_list[post.id] = Comment.objects.filter(post=post)

        return render(request, 'posts/like.html', {
            'like_list': like_list,
            'post': post,
            'comment_list': comment_list
        })

mysite/templates/posts/delete.html
{% extends 'base/app.html' %}
{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-12">
      <form method="post">
        {% csrf_token %}
        <p>削除します。よろしいですか？</p>
        <input class="btn btn-danger" type="submit" value="削除する">
      </form>
    </div>
  </div>
</div>
{% endblock %}

mysite/templates/posts/index.html
{% extends "base/app.html" %}

{% load custom_filter %}

{% block contents %}
<!-- timeline section-->
<section>
    <div class="container">
        <!-- もし投稿があれば一覧を表示する -->
        {% if post_list %}
        {% for post in post_list %}
        <div class="row p-10 text-lefti">
            <div class="col-10 offset-1">
                {% if user.id == post.author.id %}
                <div class="card" style="background-color:#EEEEEE;">
                    {% else %}
                    <div class="card">
                        {% endif %}
                        <ul class="list-group list-group-flush">
                        </ul>
                        <div class="usernameicon">
                            {% if post.author.icon %}
                            <img src=" {{post.author.icon.url}}" class="iconcss">
                            {% endif %}
                            <span class="mr-2">
                                <a class="nav-link"
                                    href="/accounts/{{ post.author.username }}">　{{ post.author.username }}</a>
                            </span>
                        </div>
                        <div class="card-body">
                            <div class="card-hedder">
                                <div class="box_left bigsize">
                                    {{ post.title }}
                                </div>
                                <br>
                                <p>
                                    {{ post.text|linebreaksbr }}
                                </p>
                                {% if post.picture %}
                                <img src="{{post.picture.url}}" class="card-img" />
                                {% endif %}
                                <div class="pt-2">
                                    <small>
                                        {{ post.created_at|date:'Y-m-d H:i' }}
                                    </small>
                                </div>

                                <br>
                                <div class="card-footer">

                                    <div class="like_list_{{post.id}} box_left">
                                        <!-- ここにお気に入り機能を実装していく -->
                                        {{ post|is_like:user }}
                                        {{ like_list|get_likes:post.id }}
                                        {{ comment_list|get_comment_list:post.id|linebreaksbr }}
                                    </div>

                                    {% if user.id != post.author.id %}
                                    <details>
                                        <summary>コメントする</summary>
                                        <hr>
                                        <form class="comment" id="{{post.id}}">
                                            {% csrf_token %}
                                            <textarea class="form-control col-12" name="comment" cols="50"
                                                rows="10"></textarea>
                                            <input type="submit" value="送信" class="comment" name='comment'>
                                        </form>
                                    </details>
                                    {% endif %}
                                </div>

                                {% if login_user == post.author %}
                                <a class="btn btn-danger" id="delete" href="{{post.id}}/delete">削除</a>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="row p-5">
                <div class="col-6 offset-3 text-center">
                    <div class="jumbotron jumbotron-fluid">
                        <div class="container">
                            <p class="lead"><a href="{% url 'posts:new' %}">投稿</a>して他のユーザーに見つけてもらおう</p>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
</section>
<!-- ここにJSスクリプトを書いていく -->

<script>
    $(document)
        .on('click', '.like', function () {
            var id = $(this).attr("id");
            do_like(id)
        }) // このセミコロンを削除
        // ここから新規追加
        .on('submit', 'form', function () {
            do_comment($(this))
            $(this).find("textarea").val("")
            return false
        });
    // 新規追加ここまで
    function do_like(post_id) {
        $.ajax({
            url: `./${post_id}/like`,
            type: 'get'
        })
            .done((data) => {
                console.log(data)

                $('.like_list_' + post_id).html(data);
            })
    }
    // 新規追加
    function do_comment(form) {
        console.log(form.serialize())
        $.ajax({
            url: `./${form.attr("id")}/comment/`,
            type: 'post',
            data: form.serialize(),
        })
            .done((data) => {
                $('.like_list_' + form.attr("id")).html(data);
            })
    }
    // 新規追加ここまで


</script>
{% endblock contents %}

mysite/templates/posts/like.html
{% load custom_filter %}
{{ post|is_like:user }}
{{ like_list|get_likes:post.id }}

<br>
{{ comment_list|get_comment_list:post.id|linebreaksbr }}

mysite/templates/posts/new.html
{% extends "base/app.html" %}
{% block contents %}
<div class="center-block container col-8 offset-2">
    <h2>新規投稿</h2>
    <form id="signupform" action="{% url 'posts:new' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="custom-file">
                {{form.picture}}
            </div>
            {% if form.picture.errors %}
            <div class="alert alert-danger">
                {{ form.picture.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="title">タイトル</label>
            <div>
                {{form.title}}
            </div>
            {% if form.title.errors %}
            <div class="alert alert-danger">
                {{ form.title.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="text">メッセージ</label>
            <textarea class="form-control" name="text" cols="40" rows="10" id="id_text"></textarea>
            {% if form.text.errors %}
            <div class="alert alert-danger">
                {{ form.text.errors }}
            </div>
            {% endif %}
        </div>
        <div class="form-group">
            <input type="submit" value="投稿" class="btn btn-primary form-control">
        </div>
    </form>
</div>


{% endblock contents %}