mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('<username>/', views.AccountDetailView.as_view(), name='userdetail'),
    path('icon/edit/', views.IconEdit.as_view(), name='icon_edit'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/posts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'posts'

urlpatterns = [
    path('new/', login_required(views.New.as_view()), name='new'),
    path('', login_required(views.Index.as_view()), name='index'),
    path('<postId>/like/', login_required(views.Likes.as_view()), name='like'),
    path('<postId>/comment/',
         login_required(views.AddComment.as_view()), name='comment'),
    path('<int:pk>/delete/',
         login_required(views.PostDelete.as_view()), name='delete'),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class User(AbstractUser):
    icon = models.ImageField(
        upload_to="image/", blank=True, null=True, default='default/e-go.jpg')
    message = models.TextField(blank=True, null=True)
    twitter_url = models.URLField(
        max_length=300, default='https://twitter.com/')

    def get_absolute_url(self):
        return reverse('sample: profile', kwargs={'username': self.username})

mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.validators import MinLengthValidator
from django.utils.translation import ugettext_lazy
from .models import User
class SignUpForm(UserCreationForm):
    class Meta:
        # 使うモデルの指定です。定義したものを使います。
        model = User
        # ここではフォームで入力するフィールドを指定しています。
        fields = ("username", "password1", "password2", "icon", "message", "twitter_url")
    # 入力したパスワードの検証(バリデーション)を行っています
    def clean_password(self):
        # 入力されたパスワードを取得します
        password = self.cleaned_data.get('password1')
        # 数字とアルファベットが含まれているのかチェックします。
        if not re.search(r'\d', password):
            raise forms.ValidationError('数字が含まれていません')
        if not re.search(r'[a-zA-Z]', password):
            raise forms.ValidationError('アルファベットが含まれていません')
        return password

    

mysite/accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.contrib.auth import login
from django.views.generic.edit import UpdateView

from .forms import SignUpForm
from .models import User
from posts.models import Post, Comment
from posts.views import Index
# サインアップ画面


class SignUpView(generic.CreateView):
    # 使うformクラス設定
    form_class = SignUpForm
    # 使うテンプレートファイル設定
    template_name = 'registration/signup.html'
    # 成功時にログイン処理を行ってAccountDetailViewに飛ぶ

    def get_success_url(self):
        form = self.get_form()
        # usernameから登録したユーザー情報を参照
        user = User.objects.get(username=form.data.get('username'))

        # ログイン処理を行う
        login(self.request, user)
        return reverse(
            'accounts:userdetail',
            kwargs={'username': user.username})
# アカウント詳細画面設定


class AccountDetailView(DetailView):
    model = User
    # urlのパスクエリを引数に取る(後述)
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['login_user'] = self.request.user
        context['post_list'] = Post.objects.all()
        login_user = self.request.user
        comment_list = {}
        comment_list2 = {}

        for post in context['post_list']:
            comment_list[post.id] = Comment.objects.filter(post=post)
        for post in context['post_list']:
            comments = []
            for comment in comment_list[post.id]:
                if post.author.id == login_user.id or comment.author.id == login_user.id:
                    comments.append(comment)
            comment_list2.update({post.id: comments})
        context['comment_list'] = comment_list2
        return context


class IconEdit(UpdateView):
    model = User
    template_name = 'accounts/icon_edit.html'
    fields = ['icon', 'message', 'twitter_url']

    def get_object(self):
        # ログイン中のユーザーで検索することを明示する
        return self.request.user

    def get_success_url(self):
        form = self.get_form()
        return reverse(
            'accounts:userdetail',
            kwargs={'username': self.request.user.username})

mysite/templates/accounts/icon_edit.html
{% extends 'base/app.html' %}
{% block contents %}
<div id="icon_edit"></div>
<div class="container">
    <div class=" card card-primary">
        <dl id="icon_edit_dl">
            <h1 class="card-heading" id="icon_edit_h1">
                登録フォーム
            </h1>
            <div class="card-body">
                <form action="{% url 'accounts:icon_edit' %}" method="post" enctype="multipart/form-data"
                    id="icon_edit_form">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="field">
                        <dt id="icon_edit_dt">
                            {{ form.icon.label_tag }}
                        </dt>
                        <dd id="icon_edit_dd">
                            {{ form.icon }}

                            {{ form.icon.errors }}
                        </dd>
                    </div>
                    <div class="field">
                        <dt id="icon_edit_dt">
                            {{ form.message.label_tag }}
                        </dt>
                        <dd id="icon_edit_dd">
                            {{ form.message }}

                            {{ form.message.errors }}
                        </dd>
                    </div>
                    <div class="field">
                        <dt id="icon_edit_dt">
                            {{ form.twitter_url.label_tag }}
                        </dt>
                        <dd id="icon_edit_dd">
                            {{ form.twitter_url }}

                            {{ form.twitter_url.errors }}
                        </dd>
                    </div>
                    <div class="field">
                        <button type="submit" class="btn btn-primary">更新</button>
                    </div>
                </form>
            </div>
        </dl>
    </div>
</div>
{% endblock %}

mysite/templates/accounts/user_detail.html
{% extends "base/app.html" %}

{% load custom_filter %}

{% block contents %}
<div class="container" id="user_detail">
    <!-- アカウント情報 -->
    <div class="row">
        <div class="col-md-2 col-md-offset-4">
        </div>
        <div class="col-md-9">
            {% if user.icon %}
            <img src=" {{user.icon.url}}" class="user_icon_img">
            {% endif %}
            <h2 class="detail_user_name">
                {{user.username}}
            </h2>

            <h4 class="detail_user_profile">profile</h4>

            <p>{{user.message|linebreaksbr }}</p><br>
            {% if user.id == login_user.id %}
            <h4 class="detail_user_profile">twitter</h4>
            {{user.twitter_url}} <br>

            <br>
            <a href="{% url 'accounts:icon_edit' %}">
                <button class="btn btn-secondary">
                    <i class="fas fa-cog"></i> プロフィールを編集する
                </button>
            </a>
            {% endif %}
            <hr>
            <h4 class="detail_user_profile">{{user.username}}の投稿一覧</h4>
            <hr>
            <di class="card">
                {% if post_list %}
                {% for post in post_list %}
                {% if post.author.id == user.id %}
                <div class="box_left bigsize">
                    <h3>{{ post.text }}</h3>
                </div>
                {% if post.picture %}
                <img src="{{post.picture.url}}" class="card-img" />
                {% endif %}
                <div class="pt-2">
                    <p>{{ post.created_at|date:'Y-m-d H:i' }}</p>
                    {{ comment_list|get_comment_list:post.id|linebreaksbr }}
                </div>
                <hr>

                {% endif %}
                {% endfor %}
                {% else %}
                {% endif %}
        </div>
    </div>
</div>

</div>
{% endblock contents %}